### ISSUE TITLE
Abrv field in Lookup tables 

### ISSUE THREAD

**Issue by khorvat** [math-os/mathos-scheduler#17]
Should we use Abrv field in lookup tables ?

**Comment by aljubic** [comment]
Could you tell us what are the benefits of using abrv? 
So we could decide if we should use it or not.

**Comment by khorvat** [comment]
I already explained this, on consultation we had last time, this filed's value is used as a reference in code. In case client wants to change the value of name field abrv field value should not change and therefor code changes are unnecessary. Also Abrv field is used in the code to gain strongly typed approach.

e.g.:
roleLookup.**Administrators**.Name  
roleLookup.**Administrators**.RoleId
etc.

So if client changes the value of the name field from _Administrators_ to _Admin_ Abrv should stay the same _Administrators_ and no code refactoring is needed.

Let me know if you want to use this approach or not ?

**Comment by aljubic** [comment]
Ok then, I think we misunderstood the meaning of Abrv field. We agree to use this approach.
