### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by aljubic** [math-os/mathos-scheduler#2]
Mock-up screens should be made for 
-Registration
-Login
-Add user
-Edit user
-User list
-Add role
-Edit role
-Role list

**Comment by khorvat** [comment]
@aljubic can you please describe tasks with more details, @MirnaMarkovic may not know what she should mock-up. This applies to all issues.

**Comment by MirnaMarkovic** [comment]
Here is a link for screens that are mentioned in this task: https://moqups.com/mmirna/X1HYHuAw/p:ad54c725a

**Comment by khorvat** [comment]
Sorry @MirnaMarkovic , I didn't see your notification ... mockups looks good and I think you should start building mockups for the main screens, @aljubic can you please open tasks for main screens (Schedule overview, Class room availability, Execution plan screens etc.) ?

**Comment by khorvat** [comment]
Also @MirnaMarkovic and @aljubic when you are finished with the task please reassign the task to one that should review the task this way everyone can maintain their task list.
