### ISSUE TITLE
Project running issue

### ISSUE THREAD

**Issue by aljubic** [math-os/mathos-scheduler#32]
pri pokretanju aplikacije dobijemo error:
HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.

a slijedeći upute u detaljima dolazimo do sljedeće greške:

Server Error in '/' Application.
The inline constraint resolver of type 'DefaultInlineConstraintResolver' was unable to resolve the following inline constraint: 'string'

u kojemu nam kaže da je greška u WebAPI\Global.asax.cs
na liniji 19:
Line 17:         {
Line 18:             AreaRegistration.RegisterAllAreas();
Line 19:             GlobalConfiguration.Configure(WebApiConfig.Register);
Line 20:             FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
Line 21:             RouteConfig.RegisterRoutes(RouteTable.Routes);

**Comment by khorvat** [comment]
Can you please try to provide us with code that is causing the issue (probably few lines of your routing configuration) and in the meanwhile take a look at the following post: http://stackoverflow.com/questions/23412021/defaultinlinecontraintresolver-error-in-webapi-2

**Comment by aljubic** [comment]
I commented out all mvc references and changed folder structure, but I still get the same error.

**Comment by khorvat** [comment]
I have pushed latest version to the repository including the following changes:

MVC reference has been removed from the WebAPI project
The bug related to inline string constraint is fixed
Removed HelpPages as they were dependent of MVC

Now you need to fix the Ninject binding issues in order to run your controllers, also It will be great to use CodeMaid VS plugin so you can have consistent code formatting across the whole team.

http://www.codemaid.net/

**Comment by aljubic** [comment]
I fixed binding issues, but still getting error that says:

Could not load file or assembly 'System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by khorvat** [comment]
I have fixed the error above and few more issues I have found. In the future you and your team should to handle this kind of issues as you need to learn your way around the WebAPI,

It is important for you and the team to review my changes in this commit so you can move forward.

Regards

**Comment by aljubic** [comment]
Running properly now, thanks!
